# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
!jupyter nbextension enable --py --sys-prefix widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

In [2]:
!pip install gmaps

Requirement already satisfied: gmaps in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (0.9.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (7.5.1)
Requirement already satisfied: six in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (1.15.0)
Requirement already satisfied: ipython>=5.3.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (7.16.1)
Requirement already satisfied: geojson>=2.0.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (2.5.0)
Requirement already satisfied: traitlets>=4.3.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (4.3.3)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->gmaps) (5.3.2)
Requirement already satisfied: nbformat>=4.2.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->gmaps) (5.0.7)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (3.0.5)
Requirement already satisfied: jedi>=0.10 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.17.1)
Requirement already satisfied: decorator in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (4.4.2)
Requirement already satisfied: backcall in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: pygments in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (2.6.1)
Requirement already satisfied: pickleshare in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (49.2.0.post20200714)
Requirement already satisfied: pexpect; sys_platform != "win32" in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (4.8.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.1.0)
Requirement already satisfied: ipython-genutils in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from traitlets>=4.3.0->gmaps) (0.2.0)
Requirement already satisfied: tornado>=4.2 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.0.4)
Requirement already satisfied: jupyter-client in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.6)
Requirement already satisfied: jupyter-core in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.6.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: notebook>=4.4.1 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.0.3)
Requirement already satisfied: wcwidth in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from jedi>=0.10->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.3.0->gmaps) (0.6.0)
Requirement already satisfied: pyzmq>=13 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (19.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: attrs>=17.4.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.16.0)
Requirement already satisfied: prometheus-client in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.0)
Requirement already satisfied: nbconvert in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.6.1)
Requirement already satisfied: jinja2 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.2)
Requirement already satisfied: terminado>=0.8.1 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.3)
Requirement already satisfied: Send2Trash in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.2)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: defusedxml in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.6.0)
Requirement already satisfied: bleach in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.1.5)
Requirement already satisfied: testpath in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4.4)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: webencodings in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: packaging in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.4)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/calvarez17/opt/anaconda3/lib/python3.8/site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.4.7)

In [3]:
!jupyter nbextension enable --py --sys-prefix gmaps

Enabling notebook extension jupyter-gmaps/extension...
      - Validating: OK

In [4]:
!jupyter nbextension enable --py gmaps

Enabling notebook extension jupyter-gmaps/extension...
      - Validating: OK

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import os
import gmaps
import json
import time




# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [6]:
weather_data = pd.read_csv("../WeatherPy/output_data/cities.csv")
weather_data.head()

,Country,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,AF,Nuristan,35.30,70.83,27.59,86,0,7.34,1602704708
1,ZA,Hermanus,-34.42,19.23,61.00,74,0,5.01,1602704708
2,AR,Ushuaia,-54.80,-68.30,48.20,57,40,12.75,1602704691
3,GL,Qaanaaq,77.48,-69.36,30.56,85,45,6.87,1602704709
4,PF,Rikitea,-23.12,-134.97,73.63,80,27,19.46,1602704419

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [19]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Store latitude and longitude in locations
locations = weather_data[["Latitude", "Longitude"]].astype(float)

# Store Humidity in humidity
humidity = weather_data["Humidity"]

In [20]:
#Create the heatmap
fig = gmaps.figure()
max_intensity = np.max(humidity)

#Heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=100, point_radius=1)

# Add layer
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [10]:
# Narrow down the cities with wind speed less than 10 mph, cloudiness equals to 0 and max temp between 70 and 80
weather_criteria = weather_data.loc[(weather_data["Wind Speed"] <= 10) & (weather_data["Cloudiness"] == 0) & \
                                   (weather_data["Max Temp"] >= 70) & (weather_data["Max Temp"] <= 80)].dropna()

weather_criteria

,Country,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Date
8,MZ,Cuamba,-14.80,36.54,73.89,51,0,8.66,1602704710
118,OM,Sur,22.57,59.53,77.79,44,0,8.88,1602704749
197,ZA,Upington,-28.45,21.26,78.80,21,0,3.36,1602704776
285,ZM,Namwala,-15.75,26.44,77.38,47,0,8.21,1602704807
286,SA,Buraidah,26.33,43.98,75.20,29,0,4.70,1602704726
335,BW,Kanye,-24.97,25.33,71.55,34,0,7.18,1602704821
363,LY,Ubari,26.59,12.78,78.57,27,0,5.57,1602704828
428,IL,Kiryat Gat,31.61,34.76,77.00,84,0,4.29,1602704582
446,LY,Benghazi,32.12,20.07,72.09,58,0,6.80,1602704850
485,BR,Entre Rios,-11.94,-38.08,79.03,59,0,8.66,1602704861
524,TZ,Chake Chake,-5.25,39.77,78.06,81,0,9.35,1602704870

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [11]:
#Create the hotel_df
hotel_df = weather_criteria.loc[:,["City","Country", "Latitude", "Longitude"]]

# Add a "Hotel Name" column to the DataFrame.
hotel_df["Hotel Name"] = ""

# Display the result
hotel_df

            City Country  Latitude  Longitude Hotel Name
8         Cuamba      MZ    -14.80      36.54
118          Sur      OM     22.57      59.53
197     Upington      ZA    -28.45      21.26
285      Namwala      ZM    -15.75      26.44
286     Buraidah      SA     26.33      43.98
335        Kanye      BW    -24.97      25.33
363        Ubari      LY     26.59      12.78
428   Kiryat Gat      IL     31.61      34.76
446     Benghazi      LY     32.12      20.07
485   Entre Rios      BR    -11.94     -38.08
524  Chake Chake      TZ     -5.25      39.77

In [12]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

In [13]:
for index, row in hotel_df.iterrows():
    # get city name, latitude, longitude from df
    latitude = row["Latitude"]
    longitude = row["Longitude"]
    city_name = row["City"]
    
    # create the parameters
    params["location"] = f"{latitude},{longitude}"

    # make api request
    print(f"Retrieving Desired Data {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    # save the hotel name to dataframe
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']

    # if there is no hotel available, show missing field
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")
    
    # Wait 1 sec to make another api request to avoid SSL Error
    time.sleep(1)

# Print end of search once searching is completed
print("-------End of Search-------")

Retrieving Desired Data 8: Cuamba.
Closest hotel in Cuamba is Daania Residence.
------------
Retrieving Desired Data 118: Sur.
Closest hotel in Sur is Sur Plaza Hotel.
------------
Retrieving Desired Data 197: Upington.
Closest hotel in Upington is Allianto Boutique Hotel & Spa.
------------
Retrieving Desired Data 285: Namwala.
Missing field/result... skipping.
------------
Retrieving Desired Data 286: Buraidah.
Closest hotel in Buraidah is فندق براند القصيم.
------------
Retrieving Desired Data 335: Kanye.
Closest hotel in Kanye is Ga-Thuli Guest House.
------------
Retrieving Desired Data 363: Ubari.
Closest hotel in Ubari is فندق أوباري.
------------
Retrieving Desired Data 428: Kiryat Gat.
Closest hotel in Kiryat Gat is Desert Gat.
------------
Retrieving Desired Data 446: Benghazi.
Closest hotel in Benghazi is فندق نزل الراحة.
------------
Retrieving Desired Data 485: Entre Rios.
Closest hotel in Entre Rios is OYO Hotel Portal da Cidade.
------------
Retrieving Desired Data 524: Chake Chake.
Closest hotel in Chake Chake is Pemba Misali Sunset Beach.
------------
-------End of Search-------

In [14]:
#Show our df with the new Hotel Name Values
hotel_df

            City Country  Latitude  Longitude                     Hotel Name
8         Cuamba      MZ    -14.80      36.54               Daania Residence
118          Sur      OM     22.57      59.53                Sur Plaza Hotel
197     Upington      ZA    -28.45      21.26  Allianto Boutique Hotel & Spa
285      Namwala      ZM    -15.75      26.44
286     Buraidah      SA     26.33      43.98              فندق براند القصيم
335        Kanye      BW    -24.97      25.33           Ga-Thuli Guest House
363        Ubari      LY     26.59      12.78                    فندق أوباري
428   Kiryat Gat      IL     31.61      34.76                     Desert Gat
446     Benghazi      LY     32.12      20.07                فندق نزل الراحة
485   Entre Rios      BR    -11.94     -38.08     OYO Hotel Portal da Cidade
524  Chake Chake      TZ     -5.25      39.77      Pemba Misali Sunset Beach

In [15]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [16]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))